---
# Install main packages
# TODO Pin (hold) version?
- name: Kea | Debian | Install main packages
  ansible.builtin.package:
    name: "{{ kea_dhcp_packages if not kea_dhcp_packages_set_version
              else kea_dhcp_packages | product([kea_dhcp_repo_version ~ '*']) | map('join', '=') | list }}"
    state: present
  ignore_errors: "{{ ansible_check_mode }}"
  notify:
    - Kea | Restart services
  when: kea_dhcp_packages
  register: kea_dhcp_packages_changed
  tags:
    - install
    - kea-dhcp
    - kea-dhcp-install

# Install extra packages
- name: Kea | Debian | Install extra packages
  ansible.builtin.package:
    name: "{{ kea_dhcp_extra_packages }}"
    state: present
  ignore_errors: "{{ ansible_check_mode }}"
  when: kea_dhcp_extra_packages
  tags:
    - install
    - kea-dhcp
    - kea-dhcp-install
