---
# Install main packages
# TODO Reconsider - do we really need fallback install tasks?
- name: Kea | Generic | Install main packages
  ansible.builtin.package:
    name: "{{ kea_dhcp_packages }}"
    state: present
  ignore_errors: "{{ ansible_check_mode }}"
  notify:
    - Kea | Restart services
  when: kea_dhcp_packages
  register: kea_dhcp_packages_changed
  tags:
    - install
    - kea-dhcp
    - kea-dhcp-install

# Install extra packages
- name: Kea | Generic | Install extra packages
  ansible.builtin.package:
    name: "{{ kea_dhcp_extra_packages }}"
    state: present
  ignore_errors: "{{ ansible_check_mode }}"
  when: kea_dhcp_extra_packages
  tags:
    - install
    - kea-dhcp
    - kea-dhcp-install
