---
# Load OS specific vars
- name: Kea | Load OS-specific vars
  ansible.builtin.include_vars: "{{ lookup('ansible.builtin.first_found', params) }}"
  vars:
    params:
      files:
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      paths:
        - 'vars'
      # Don't throw errors and continue if no files found
      skip: true

# Always required because they are used in a task to setup or remove a repository
- name: Kea | Load OS-specific vars with ISC repository parameters
  ansible.builtin.include_vars: "{{ lookup('ansible.builtin.first_found', params) }}"
  vars:
    params:
      files:
        - '{{ ansible_distribution }}-isc-repo.yml'
        - '{{ ansible_os_family }}-isc-repo.yml'
      paths:
        - 'vars'
      skip: true

# Only required when ISC repository enabled to override some defaults
- name: Kea | Load OS-specific vars when ISC repository enabled
  ansible.builtin.include_vars: "{{ lookup('ansible.builtin.first_found', params) }}"
  vars:
    params:
      files:
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      paths:
        - 'vars/isc-repo'
      skip: true
  when: kea_dhcp_isc_repo_ensure == 'present'

- name: Kea | Define kea_dhcp_repo_map
  ansible.builtin.set_fact:
    kea_dhcp_repo_map: "{{ __kea_dhcp_repo_map }}"
  when: kea_dhcp_repo_map is not defined

- name: Kea | Define kea_dhcp_services
  ansible.builtin.set_fact:
    kea_dhcp_services: "{{ __kea_dhcp_services }}"
  when: kea_dhcp_services is not defined

- name: Kea | Define package variables
  ansible.builtin.set_fact:
    kea_dhcp_prereq_pkgs: "{{ kea_dhcp_prereq_pkgs if kea_dhcp_prereq_pkgs is defined else __kea_dhcp_prereq_pkgs }}"
    kea_dhcp_packages: "{{ kea_dhcp_packages if kea_dhcp_packages is defined else __kea_dhcp_packages }}"
    kea_dhcp_extra_packages: "{{ kea_dhcp_extra_packages if kea_dhcp_extra_packages is defined else __kea_dhcp_extra_packages }}"

- name: Kea | Debian | Define repo variables
  ansible.builtin.set_fact:
    kea_dhcp_repo_key_gpg: |-
      {{ kea_dhcp_repo_key_gpg if kea_dhcp_repo_key_gpg is defined
          else kea_dhcp_repo_map[kea_dhcp_repo_version]['key_gpg'] }}
    kea_dhcp_repo_key_url: |-
      {{ kea_dhcp_repo_key_url if kea_dhcp_repo_key_url is defined
          else kea_dhcp_repo_map[kea_dhcp_repo_version]['key_url'] }}
    kea_dhcp_repo_keyring_file: |-
      {{ kea_dhcp_repo_keyring_file if kea_dhcp_repo_keyring_file is defined
          else kea_dhcp_repo_map[kea_dhcp_repo_version]['keyring_file'] }}
    kea_dhcp_repo_deb: >-
      {{ kea_dhcp_repo_deb if kea_dhcp_repo_deb is defined
          else 'deb [signed-by=' ~ kea_dhcp_repo_map[kea_dhcp_repo_version]['keyring_file'] ~ '] '
          ~ kea_dhcp_repo_map[kea_dhcp_repo_version]['repo_deb'] }}
    kea_dhcp_repo_deb_src: >-
      {{ kea_dhcp_repo_deb_src if kea_dhcp_repo_deb_src is defined
          else 'deb-src [signed-by=' ~ kea_dhcp_repo_map[kea_dhcp_repo_version]['keyring_file'] ~ '] '
          ~ kea_dhcp_repo_map[kea_dhcp_repo_version]['repo_deb_src'] }}
    kea_dhcp_repo_file: |-
      {{ kea_dhcp_repo_file if kea_dhcp_repo_file is defined
          else kea_dhcp_repo_map[kea_dhcp_repo_version]['file'] }}
    kea_dhcp_repo_template: |-
      {{ kea_dhcp_repo_template if kea_dhcp_repo_template is defined
          else kea_dhcp_repo_map[kea_dhcp_repo_version]['template'] }}
  when:
    - ansible_os_family == "Debian"
